public class EmployeetTrigHandler {
    /*
    public static void gendercheck(List<Employee__c> oldList){
        for(Employee__c emp:oldList){
            if(emp.Gender__c == 'Male'){
                emp.addError('Male Candidates Cannot be deleted');
            }
        }
    }
    
    public static void updatedList(List<Employee__c> oldList){
        integer empCount = [Select count() from Employee__c];
        System.debug('EmpListCount: '+empCount);
    }
*/

}